target 'FreJun'
pod 'Google/SignIn'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'HotlineSDK'
pod 'Amplitude-iOS', '~> 3.7.0'
pod 'OneSignal'
